#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='oni2'
export VISUAL='oni2'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

## standardml per comment https://stackoverflow.com/questions/60179356/how-do-you-setup-standardml-on-macos-catalina
export PATH=/usr/local/smlnj/bin:$PATH

# Haskell/Stack has been installed to: /usr/local/bin/stack
# NOTE: You may need to run 'xcode-select --install' and/or
# WARNING: '/Users/mandalarian/.local/bin' is not on your PATH.
# For best results, please add it to the beginning of PATH in your profile.

export PATH=/usr/local/bin:$PATH
export PATH=/Users/mandalarian/.local/bin:$PATH
export PATH="$HOME/.cargo/bin:$PATH"
