code --install-extension alexdima.copy-relative-path
code --install-extension EditorConfig.EditorConfig
code --install-extension eamodio.gitlens
code --install-extension formulahendry.code-runner
code --install-extension formulahendry.auto-close-tag
code --install-extension ms-vscode.typescript-javascript-grammar
code --install-extension esbenp.prettier-vscode
code --install-extension eg2.vscode-npm-script
code --install-extension christian-kohler.npm-intellisense
code --install-extension rbbit.typescript-hero
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wix.vscode-import-cost
code --install-extension steoates.autoimport
code --install-extension pmneo.tsimporter
code --install-extension quicktype.quicktype
code --install-extension wayou.vscode-todo-highlight
code --install-extension techer.open-in-browser
code --install-extension stringham.move-ts
code --install-extension Zignd.html-css-class-completion